apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat-service
  template:
    metadata:
      labels:
        app: cat-service
    spec:
      containers:
        - name: cat-service
          image: shiragin/cat-service-k8s:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4002
