apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  template:
    spec:
      containers:
        - name: migration
          image: shiragin/backend-k8s:latest
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: express_postgres_db
            - name: POSTGRES_HOST
              value: database-service
            - name: POSTGRES_PORT
              value: '5432'
          command: ['npx', 'sequelize-cli', 'db:migrate']
      restartPolicy: OnFailure
