"""initial migration

Revision ID: d46cb0a5092d
Revises: 
Create Date: 2023-07-26 08:18:36.541207

"""
from alembic import op
from sqlalchemy import text
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd46cb0a5092d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SEQUENCE id_seq START = 1 INCREMENT = 1;')

    op.create_table('catpic',
    sa.Column('id', sa.Integer(), server_default=text("id_seq.nextval"), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='PUBLIC'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catpic', schema='PUBLIC')
    op.execute('DROP SEQUENCE IF EXISTS id_seq;')
    # ### end Alembic commands ###

