version: '3.4'
volumes:
  db-data:
services:
  ##############################
  # Database Container
  ##############################
  database-k8s:
    image: postgres:13
    container_name: database-k8s
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: express_postgres_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - '5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5