apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: syanay/cat-app-frontend
          env:
            - name: VITE_BACKEND_URL
              value: /api/
          ports:
            - containerPort: 4001
