apiVersion: v1
kind: Secret
metadata:
  name: snowflake-secrets
type: Opaque
data:
  user: aW5zYWl0
  password: SW5zYWl0MTIz

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  user: cG9zdGdyZXM=  
  password: cG9zdGdyZXM= 